id: sync_from_git
namespace: prod

tasks:
  - id: git
    type: io.kestra.plugin.git.Sync
    url: https://github.com/kestra-io/scripts
    branch: main
    username: anna-geller
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"