id: push_to_git
namespace: prod

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.Push
    namespaceFiles:
      enabled: true
    flows:
      enabled: true
    url: https://github.com/kestra-io/scripts
    branch: myflows
    username: anna-geller
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    commitMessage: "add flows and scripts {{ now() }}"

triggers:
  - id: schedule_push
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/15 * * * *"